language: node_js
os:
  - linux
node_js:
  - '8'
install: true
script: true
before_deploy: true
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
    on:
      all_branches: true
